// Important: this file is auto-generated by flowerbi.

import {
  BasicQueryColumn,
  NumberQueryColumn,
} from './src/QueryColumn-Extensions'

export const ProductSubcategory = {
  ProductSubcategoryID: new NumberQueryColumn(
    'ProductSubcategory.ProductSubcategoryID'
  ),
  Name: new BasicQueryColumn<string>('ProductSubcategory.Name'),
}

export const Product = {
  ProductId: new NumberQueryColumn('Product.ProductId'),
  Name: new BasicQueryColumn<string>('Product.Name'),
  ProductSubcategoryID: new NumberQueryColumn('Product.ProductSubcategoryID'),
}

export const AdventureWorks2019Schema = {
  ProductSubcategory,
  Product,
}
